lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin de la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Chemin de la clé publique
    pass_phrase: '%env(JWT_PASSPHRASE)%'
